### ISSUE TITLE
Postgres compatibility?

### ISSUE THREAD

**Issue by sjcallender** [masugadesign/cp-filters-craft-cms#9] opened 2020-12-10 17:36 UTC
**Describe the bug**  
Just installed on a site using Postgres and these are the screens we see. Wondering if the plugin is compatible with Postgres or if it's a different issue?

![image](https://user-images.githubusercontent.com/984311/101808101-e6da8580-3ae3-11eb-9c60-796da6fd435e.png)

![image](https://user-images.githubusercontent.com/984311/101808169-fe197300-3ae3-11eb-9dd8-17c3c1fea361.png)

**Craft Version & Installed Plugin Version**  
Craft: 3.5.16
Plugin: 1.0.1.1

**To Reproduce**  
_Steps to reproduce the behavior:_
1. Install on a site using Postgres and visit the two admin views for the plugin.

**Expected behavior**  
Expected to settings on the settings view and no errors on the plugin view.

**Comment by benjaminkohl** [comment] 2020-12-10 18:57
This is a duplicate of issue 5 which will be fixed in the next release but you can also fix it now by following the instructions in [this comment](https://github.com/masugadesign/cp-filters-craft-cms/issues/5#issuecomment-727050543).

**Closed as completed by benjaminkohl** 2020-12-10 18:57 UTC
Labels: bug

**Comment by sjcallender** [comment] 2020-12-10 22:25
Thanks @benjaminkohl. Sorry for the dupe!
